//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/input/SelectionInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/input/SelectionInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @SelectionInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @SelectionInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""SelectionInputActions"",
    ""maps"": [
        {
            ""name"": ""Selection"",
            ""id"": ""79d9a56a-9655-4220-af8b-cebce4dc8dd4"",
            ""actions"": [
                {
                    ""name"": ""P1Previous"",
                    ""type"": ""Button"",
                    ""id"": ""bb666a4c-e9e9-4dca-a3fc-6efef773cbb7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Next"",
                    ""type"": ""Button"",
                    ""id"": ""27dad057-7e90-4957-9089-fd04f9a85f47"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""a435df11-a1fd-49f1-a56d-dcbadcae085d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Previous"",
                    ""type"": ""Button"",
                    ""id"": ""a2cc6404-10fd-4c89-871c-ac1b757397e0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Next"",
                    ""type"": ""Button"",
                    ""id"": ""b88bd149-9eeb-4a04-8bf4-6aecff542a57"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""98d9bf37-3b30-455c-9d5c-7b046f26bc34"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c166446e-c0f7-4282-a749-0aab931544ac"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Previous"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""588a8997-781f-4118-b312-1fc140784b69"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4caa5c51-de69-41a8-895f-dee2487cd0d3"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df977ad3-e0e2-40d2-99ae-3c305b84d934"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Previous"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""458ab8ab-db30-4c3d-8f75-d9eb17047257"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ca8fd7d-e3b1-421e-9f12-746640511a49"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Selection
        m_Selection = asset.FindActionMap("Selection", throwIfNotFound: true);
        m_Selection_P1Previous = m_Selection.FindAction("P1Previous", throwIfNotFound: true);
        m_Selection_P1Next = m_Selection.FindAction("P1Next", throwIfNotFound: true);
        m_Selection_P1Confirm = m_Selection.FindAction("P1Confirm", throwIfNotFound: true);
        m_Selection_P2Previous = m_Selection.FindAction("P2Previous", throwIfNotFound: true);
        m_Selection_P2Next = m_Selection.FindAction("P2Next", throwIfNotFound: true);
        m_Selection_P2Confirm = m_Selection.FindAction("P2Confirm", throwIfNotFound: true);
    }

    ~@SelectionInputActions()
    {
        UnityEngine.Debug.Assert(!m_Selection.enabled, "This will cause a leak and performance issues, SelectionInputActions.Selection.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Selection
    private readonly InputActionMap m_Selection;
    private List<ISelectionActions> m_SelectionActionsCallbackInterfaces = new List<ISelectionActions>();
    private readonly InputAction m_Selection_P1Previous;
    private readonly InputAction m_Selection_P1Next;
    private readonly InputAction m_Selection_P1Confirm;
    private readonly InputAction m_Selection_P2Previous;
    private readonly InputAction m_Selection_P2Next;
    private readonly InputAction m_Selection_P2Confirm;
    /// <summary>
    /// Provides access to input actions defined in input action map "Selection".
    /// </summary>
    public struct SelectionActions
    {
        private @SelectionInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SelectionActions(@SelectionInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Selection/P1Previous".
        /// </summary>
        public InputAction @P1Previous => m_Wrapper.m_Selection_P1Previous;
        /// <summary>
        /// Provides access to the underlying input action "Selection/P1Next".
        /// </summary>
        public InputAction @P1Next => m_Wrapper.m_Selection_P1Next;
        /// <summary>
        /// Provides access to the underlying input action "Selection/P1Confirm".
        /// </summary>
        public InputAction @P1Confirm => m_Wrapper.m_Selection_P1Confirm;
        /// <summary>
        /// Provides access to the underlying input action "Selection/P2Previous".
        /// </summary>
        public InputAction @P2Previous => m_Wrapper.m_Selection_P2Previous;
        /// <summary>
        /// Provides access to the underlying input action "Selection/P2Next".
        /// </summary>
        public InputAction @P2Next => m_Wrapper.m_Selection_P2Next;
        /// <summary>
        /// Provides access to the underlying input action "Selection/P2Confirm".
        /// </summary>
        public InputAction @P2Confirm => m_Wrapper.m_Selection_P2Confirm;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Selection; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SelectionActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SelectionActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SelectionActions" />
        public void AddCallbacks(ISelectionActions instance)
        {
            if (instance == null || m_Wrapper.m_SelectionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SelectionActionsCallbackInterfaces.Add(instance);
            @P1Previous.started += instance.OnP1Previous;
            @P1Previous.performed += instance.OnP1Previous;
            @P1Previous.canceled += instance.OnP1Previous;
            @P1Next.started += instance.OnP1Next;
            @P1Next.performed += instance.OnP1Next;
            @P1Next.canceled += instance.OnP1Next;
            @P1Confirm.started += instance.OnP1Confirm;
            @P1Confirm.performed += instance.OnP1Confirm;
            @P1Confirm.canceled += instance.OnP1Confirm;
            @P2Previous.started += instance.OnP2Previous;
            @P2Previous.performed += instance.OnP2Previous;
            @P2Previous.canceled += instance.OnP2Previous;
            @P2Next.started += instance.OnP2Next;
            @P2Next.performed += instance.OnP2Next;
            @P2Next.canceled += instance.OnP2Next;
            @P2Confirm.started += instance.OnP2Confirm;
            @P2Confirm.performed += instance.OnP2Confirm;
            @P2Confirm.canceled += instance.OnP2Confirm;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SelectionActions" />
        private void UnregisterCallbacks(ISelectionActions instance)
        {
            @P1Previous.started -= instance.OnP1Previous;
            @P1Previous.performed -= instance.OnP1Previous;
            @P1Previous.canceled -= instance.OnP1Previous;
            @P1Next.started -= instance.OnP1Next;
            @P1Next.performed -= instance.OnP1Next;
            @P1Next.canceled -= instance.OnP1Next;
            @P1Confirm.started -= instance.OnP1Confirm;
            @P1Confirm.performed -= instance.OnP1Confirm;
            @P1Confirm.canceled -= instance.OnP1Confirm;
            @P2Previous.started -= instance.OnP2Previous;
            @P2Previous.performed -= instance.OnP2Previous;
            @P2Previous.canceled -= instance.OnP2Previous;
            @P2Next.started -= instance.OnP2Next;
            @P2Next.performed -= instance.OnP2Next;
            @P2Next.canceled -= instance.OnP2Next;
            @P2Confirm.started -= instance.OnP2Confirm;
            @P2Confirm.performed -= instance.OnP2Confirm;
            @P2Confirm.canceled -= instance.OnP2Confirm;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SelectionActions.UnregisterCallbacks(ISelectionActions)" />.
        /// </summary>
        /// <seealso cref="SelectionActions.UnregisterCallbacks(ISelectionActions)" />
        public void RemoveCallbacks(ISelectionActions instance)
        {
            if (m_Wrapper.m_SelectionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SelectionActions.AddCallbacks(ISelectionActions)" />
        /// <seealso cref="SelectionActions.RemoveCallbacks(ISelectionActions)" />
        /// <seealso cref="SelectionActions.UnregisterCallbacks(ISelectionActions)" />
        public void SetCallbacks(ISelectionActions instance)
        {
            foreach (var item in m_Wrapper.m_SelectionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SelectionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SelectionActions" /> instance referencing this action map.
    /// </summary>
    public SelectionActions @Selection => new SelectionActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Selection" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SelectionActions.AddCallbacks(ISelectionActions)" />
    /// <seealso cref="SelectionActions.RemoveCallbacks(ISelectionActions)" />
    public interface ISelectionActions
    {
        /// <summary>
        /// Method invoked when associated input action "P1Previous" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Previous(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P1Next" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Next(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P1Confirm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Confirm(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P2Previous" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Previous(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P2Next" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Next(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P2Confirm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Confirm(InputAction.CallbackContext context);
    }
}
